export const ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  AGENT: 'AGENT',
};

export const AGENT_SUB_ROLES = {
  PROPERTY_AGENT: 'PROPERTY_AGENT',
  LEAD_AGENT: 'LEAD_AGENT',
  HYBRID_AGENT: 'PROPERTY_LEAD_AGENT',
};

export const PERMISSIONS = {
  MANAGE_BUSINESS: 'MANAGE_BUSINESS',
  MANAGE_TEAM: 'MANAGE_TEAM',
  MANAGE_BILLING: 'MANAGE_BILLING',
  VIEW_ALL_DATA: 'VIEW_ALL_DATA',
  MANAGE_PROPERTIES: 'MANAGE_PROPERTIES',
  MANAGE_LEADS: 'MANAGE_LEADS',
  MANAGE_DEALS: 'MANAGE_DEALS',
  MANAGE_DOCUMENTS: 'MANAGE_DOCUMENTS',
  MANAGE_QR: 'MANAGE_QR',
};
